//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektP4WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasy
    {
        public int Id { get; set; }
        public string Klasa { get; set; }
    }
}
