//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektP4WPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LotniskodbEntities : DbContext
    {
        public LotniskodbEntities()
            : base("name=LotniskodbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dane_Rezerwacji> Dane_Rezerwacji { get; set; }
        public virtual DbSet<Klasy> Klasy { get; set; }
        public virtual DbSet<Logowanie> Logowanie { get; set; }
        public virtual DbSet<Miasta> Miasta { get; set; }
    }
}
